/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.punchcafe.arduino.keywordgen;

import org.junit.jupiter.api.Test;

import static dev.punchcafe.arduino.keywordgen.TestConstants.ROOT_PACKAGE_PATH;
import static org.junit.jupiter.api.Assertions.*;

class KeywordGeneratorTest {
    @Test void appHasAGreeting() {
        KeywordGenerator.main(new String[]{ROOT_PACKAGE_PATH});

    }
}
