/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.punchcafe.arduino.keywordgen;

import java.nio.file.Path;
import java.util.Optional;

public class KeywordGenerator {

    public static void main(String[] args) {
        final String targetPath;
        if (args[0] == null) {
            targetPath = "./";
        } else {
            targetPath = args[0];
        }
        final var result = Optional.of(targetPath)
                .map(Path::of)
                .map(Path::toFile)
                .map(HeaderFinder::findHeaderFiles)
                .map(HeaderFileDeserializer::deserializeHeaderFiles)
                .map(ModelClassSerializer::serialise)
                .orElse("");
        System.out.println(result);
    }
}
